### ISSUE TITLE
Excuse me, what's the version of mongodb you use?

### ISSUE THREAD

**Issue by zhang123-sys** [atarss/clip-image-search#1]

**Comment by zhang123-sys** [comment]
Can MongoDB4.4 work?

**Comment by atarss** [comment]
> Can MongoDB4.4 work?

I was using MongoDB 6.0.5 during my developing.
You can download a standalone binary version of MongoDB from https://www.mongodb.com/download-center/community/releases/archive if you are not able to install MongoDB from the system package manager (e.g., without root permission).

**Comment by zhang123-sys** [comment]
Ok, can mongodb-org-server_6.0.7_amd64.deb&nbsp;work?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月18日(星期二) 晚上11:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [atarss/clip-image-search] Excuse me, what&#39;s the version of mongodb you use? (Issue #1)





  
Can MongoDB4.4 work?
  
I was using MongoDB 6.0.5 during my developing.
 You can download a standalone binary version of MongoDB from https://www.mongodb.com/download-center/community/releases/archive if you are not able to install MongoDB from the system package manager (e.g., without root permission).

**Comment by atarss** [comment]
> Ok, can mongodb-org-server_6.0.7_amd64.deb&nbsp;work?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年7月18日(星期二) 晚上11:36 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [atarss/clip-image-search] Excuse me, what&#39;s the version of mongodb you use? (Issue #1) Can MongoDB4.4 work? I was using MongoDB 6.0.5 during my developing. You can download a standalone binary version of MongoDB from https://www.mongodb.com/download-center/community/releases/archive if you are not able to install MongoDB from the system package manager (e.g., without root permission). — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

It should work well.

**Comment by zhang123-sys** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月18日(星期二) 晚上11:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [atarss/clip-image-search] Excuse me, what&#39;s the version of mongodb you use? (Issue #1)





  
Ok, can mongodb-org-server_6.0.7_amd64.deb&nbsp;work?
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年7月18日(星期二) 晚上11:36 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [atarss/clip-image-search] Excuse me, what's the version of mongodb you use? (Issue #1) Can MongoDB4.4 work? I was using MongoDB 6.0.5 during my developing. You can download a standalone binary version of MongoDB from https://www.mongodb.com/download-center/community/releases/archive if you are not able to install MongoDB from the system package manager (e.g., without root permission). — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
It should work well.
